### ISSUE TITLE
Channel.getUsers only returns the bot as User

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#127]
```
Call to getUsers will not return a set of all the users on the channel, but 
just one user, which would be the bot.

Steps to reproduce:

1. Connect the bot to a channel with several users
2. Issue a command/message to the bot
3. List all users on channel
4. Only bot name in the list

```

Original issue reported on code.google.com by `barand...@gmail.com` on 12 May 2013 at 6:03

**Comment by ironsquid** [comment]
I'm running into this issue as well. If I do something like: event.getChannel().getUsers().size() I only get information returned about the bot. There can be 20 people in the channel, but size stays at 1. There may be a different way to use getUsers() but right now its really awkward, at best.

**Comment by TheLQ** [comment]
Is this on 2.1?

**Comment by ironsquid** [comment]
2.0.1. Is 2.1 out yet? I don't see anything regarding this.

Also I changed my code to this, but the results are still the same. It only prints out the bot's nick, and no one else.

```
            Iterator<org.pircbotx.User> myIter = event.getChannel().getUsers().iterator();
            while (myIter.hasNext()){
                System.out.println(myIter.next().getNick());
            }
```

**Comment by MrKickkiller** [comment]
I have had this issue before. So I can confirm this issue.

(Since I'm using pircbot for a Twitch application I got around this)

**Comment by axelhodler** [comment]
works in v2.1

sample:

``` java
messageEvent.getChannel()
              .getUsers()
              .forEach(user -> System.out.println(user.getNick()));
```

**Comment by hoerup** [comment]
I assume it works with 2.1 or that you have found a work around - so i'm closing this old thing

**Comment by bvn13** [comment]
how to get really online users?
