### ISSUE TITLE
Enhancement to MessageEvent respond function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#155]
```
What's the problem?
1. MessageEvent can only respond with a Message to the channel the MessageEvent 
came from. It would be nice to be easily able to respond to the User in a 
PrivateMessage (I know it's possible but it's much less neat). It essentially 
just needs a sendMessage(User target, String message) method on the 
MessageEvent.
2. MessageEvent natively responds to all message with "User: message". An 
option to respond with just "message" would again be neat.

What version of the product are you using? On what operating system?
Not the latest but I've looked through the Javadoc and it's not changed in 2.0. 
Windows 7 64-bit.

Please provide any additional information below.
By no means critical and it's possible to get around but in my eyes would be a 
nice to have.


```

Original issue reported on code.google.com by `admira...@gmail.com` on 1 Dec 2013 at 9:41

**Comment by eduardog3000** [comment]
Hmm, the normal respond method still adds the "Username: " to the front.

I want to be able to take a GenericMessageEvent (because my bot's commands can be used in a channel message or pm just the same) and respond to it, without it adding "Username: " to the front.

Basically I want to be able to do something like:

``` Java
@Override
public void onGenericMessage(GenericMessageEvent event) throws Exception {
    if(event.getMessage().equals("!test")) {
        event.respond("testing");
    }
}
```

And have the message that gets sent be the same (i.e. no "Username: ") whether it is in a pm or to a channel.

**Comment by Cypherke** [comment]
event.getChannel().send().message("testing"); //send to channel
or
event.getUser().send().message("testing"); //send to user

**Comment by eduardog3000** [comment]
But GenericMessageEvent doesn't have getChannel().

**Comment by eduardog3000** [comment]
I think the simple solution should be to remove the "Username: " from the beginning of the `MessageEvent.respond();`. If someone wants the response to include the username, they can add it themselves.

**Comment by TheLQ** [comment]
Returning the message with the username has been the default for a long time.
But I've added GenericMessageEvent.respondWith() which doesn't add the prefix in any of the events. Does that work for you?

btw, that's the best name I could come up with. If you have any other suggestions I'd like to hear them
