### ISSUE TITLE
Hostname and Login Null until user speaks

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#245]
It appears that a users login and hostname is null until the aforementioned person speaks. (Using this function -> https://github.com/TechCavern/WaveTact/blob/master/src/main/java/com/techcavern/wavetact/utils/IRCUtils.java#L182

**Comment by TheLQ** [comment]
Does the server support WHO? Are you sure your checking after the WHO response finishes?

Setting the login and hostname after the user first speaks was a fallback for servers like twitch that don't support WHO or any other command to get that level of info

**Comment by jztech101** [comment]
Yes it does. I'm looking at Esper. It runs Charybdis btw

**Comment by TheLQ** [comment]
Fixed
