### ISSUE TITLE
Method to disable WHO command

### ISSUE THREAD

**Issue by tylerhasman** [pircbotx/pircbotx#248]
I am working with a IRC server that does not support the WHO command and whenever pircbotx sends  the command it gets kicked! Could we have a way to disable it?

**Comment by TheLQ** [comment]
What server does this happen on? Something custom like twitch?

**Comment by tylerhasman** [comment]
Yes on twitch

**Comment by TheLQ** [comment]
New method configuration.setOnJoinWhoEnabled added in 88e8c11
