### ISSUE TITLE
Failing to detect voiced users on synirc

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#249]
https://github.com/TechCavern/WaveTact/blob/master/src/main/java/com/techcavern/wavetact/utils/PermUtils.java#L111 

Returns false on voiced users. SynIRC (irc.synirc.net) runs Unreal

**Comment by TheLQ** [comment]
Works on my end:
- \* PircBotX (~LQ@synIRC-88AE0EF2.kya.res.rr.com) has joined #pircbotx
- TheLQ> ?test
- PircBotX> TheLQ: Levels: OP
- \* TheLQ gives voice to TheLQ
- TheLQ> ?test
- PircBotX> TheLQ: Levels: VOICE, OP
- \* TheLQ removes channel operator status from TheLQ
- TheLQ> ?test
- PircBotX> TheLQ: Levels: VOICE
- \* PircBotX has quit (Connection reset by peer)
- \* PircBotX (~LQ@synIRC-88AE0EF2.kya.res.rr.com) has joined #pircbotx
- TheLQ> ?test
- PircBotX> TheLQ: Levels: VOICE

**Comment by jztech101** [comment]
_facepalm_ Yeah, this is invalid. I purposefully ignored checking any unregistered users for their permlevels >_>
