### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by C3realGuy** [pircbotx/pircbotx#251]
Build fails using latest commit.

Java version:
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (Arch Linux build 7.u79_2.5.5-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

$ mvn install
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building pircbotx 2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ pircbotx ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-dependencies) @ pircbotx ---
[INFO] 
[INFO] --- maven-license-plugin:1.10.b1:format (default) @ pircbotx ---
[INFO] Updating license headers...
[WARNING] Unknown file extension: /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/.travis.yml
[WARNING] Unknown file extension: /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/.gitignore
[INFO] 
[INFO] --- maven-replacer-plugin:1.4.1:replace (default) @ pircbotx ---
[INFO] Replacement run on 1 file.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pircbotx ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ pircbotx ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 128 source files to /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 1.5
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/ReplayServer.java:[40,35] org.pircbotx.hooks.managers.GenericListenerManager in org.pircbotx.hooks.managers has been deprecated
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/ReplayServer.java:[40,35] org.pircbotx.hooks.managers.GenericListenerManager in org.pircbotx.hooks.managers has been deprecated
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/ReplayServer.java:[40,35] org.pircbotx.hooks.managers.GenericListenerManager in org.pircbotx.hooks.managers has been deprecated
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/ReplayServer.java:[40,35] org.pircbotx.hooks.managers.GenericListenerManager in org.pircbotx.hooks.managers has been deprecated
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/ReplayServer.java:[150,57] org.pircbotx.hooks.managers.GenericListenerManager in org.pircbotx.hooks.managers has been deprecated
[WARNING] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/cap/SASLCapHandler.java:[77,136] UTF_8 in org.apache.commons.codec.Charsets has been deprecated
[INFO] 7 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/UtilSSLSocketFactory.java:[169,46] no suitable method found for createSocket(java.net.Socket,java.io.InputStream,boolean)
    method javax.net.ssl.SSLSocketFactory.createSocket(java.net.Socket,java.lang.String,int,boolean) is not applicable
      (actual and formal argument lists differ in length)
    method javax.net.SocketFactory.createSocket(java.net.InetAddress,int,java.net.InetAddress,int) is not applicable
      (actual and formal argument lists differ in length)
    method javax.net.SocketFactory.createSocket(java.net.InetAddress,int) is not applicable
      (actual and formal argument lists differ in length)
    method javax.net.SocketFactory.createSocket(java.lang.String,int,java.net.InetAddress,int) is not applicable
      (actual and formal argument lists differ in length)
    method javax.net.SocketFactory.createSocket(java.lang.String,int) is not applicable
      (actual and formal argument lists differ in length)
    method javax.net.SocketFactory.createSocket() is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/UtilSSLSocketFactory.java:[167,9] method does not override or implement a method from a supertype
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.363 s
[INFO] Finished at: 2015-07-12T16:10:39+02:00
[INFO] Final Memory: 17M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project pircbotx: Compilation failure: Compilation failure:
[ERROR] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/UtilSSLSocketFactory.java:[169,46] no suitable method found for createSocket(java.net.Socket,java.io.InputStream,boolean)
[ERROR] method javax.net.ssl.SSLSocketFactory.createSocket(java.net.Socket,java.lang.String,int,boolean) is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] method javax.net.SocketFactory.createSocket(java.net.InetAddress,int,java.net.InetAddress,int) is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] method javax.net.SocketFactory.createSocket(java.net.InetAddress,int) is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] method javax.net.SocketFactory.createSocket(java.lang.String,int,java.net.InetAddress,int) is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] method javax.net.SocketFactory.createSocket(java.lang.String,int) is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] method javax.net.SocketFactory.createSocket() is not applicable
[ERROR](actual and formal argument lists differ in length)
[ERROR] /home/kerle/workspace/DDRFTPDv2/libs/pircbotx-master/src/main/java/org/pircbotx/UtilSSLSocketFactory.java:[167,9] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by TheLQ** [comment]
Looks like a new method was added in Java 8: createSocket(Socket s, InputStream consumed, boolean autoClose)
http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLSocketFactory.html
http://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocketFactory.html

Should be fixed in 0098109, tested on oracle jdk7. Thanks
