### ISSUE TITLE
Make WHOIS case-insensitive?

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#252]
Shocky = shocky?

**Comment by TheLQ** [comment]
What server returns valid users in a different case?

**Comment by jztech101** [comment]
Yes

**Comment by jztech101** [comment]
oh derp. @TheLQ no, I mean you send the whois in a different case, but whois returns it in teh correct case. So you send /whois jztech101, but the server returns the whois for JZTech101

**Comment by jztech101** [comment]
Never mind. Apparently it was an issue I needed to fix in my code lol
