### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by toddhainsworth** [pircbotx/pircbotx#254]
Hi all,

I'm attempting to run the example shown in the README but have hit this error. Assuming the default implementation of SLF4J (bundled as a dependency of PircBotX) is the correct one to be using, this seems odd.

As I mentioned I am running the same example as the README with Java 8 on OS X Yosemite.

The bot joins the server but does not provide any logging information. The exact error is as below:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.

This obviously makes it hard to debug any issues when developing the bot :-1: 

Any help is appreciated!

**Comment by tobciu** [comment]
Have you read the error message?

```
Failed to load class org.slf4j.impl.StaticLoggerBinder

This error is reported when the org.slf4j.impl.StaticLoggerBinder class could not be loaded into memory. This happens when no appropriate SLF4J binding could be found on the class path. Placing one (and only one) of slf4j-nop.jar, slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar on the class path should solve the problem.
SINCE 1.6.0 As of SLF4J version 1.6, in the absence of a binding, SLF4J will default to a no-operation (NOP) logger implementation.
You can download SLF4J bindings from the project download page.
```

Do you have the libraries on your classpath?

**Comment by toddhainsworth** [comment]
Sure have. 

Adding a maven dependency doesn't do that from the get go?

**Comment by tobciu** [comment]
so, the error messages says, that one of the folloing jar-files has to be on the class path: slf4j-nop.jar, slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar

pircbotx has only the folloing dependency: slf4j-api.jar (you can see this if you open the pom.xml and change the tab to 'dependency hierachy')

if you add one of the jars to your pom.xml for example 'slf4j-simple', the message is gone :)

```
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.5</version>
    </dependency>
```

**Comment by TheLQ** [comment]
Yes this is explained on the downloads page: https://github.com/TheLQ/pircbotx/wiki/Downloads#logging

You have to provide somewhere for slf4j to log its messages which depends on your specific environment: Some people use logback, others use apache commons, log4j, etc. slf4j-simple is the easiest to use

**Comment by toddhainsworth** [comment]
Thanks @TheLQ, must have missed that! Thanks for the POM example tobciu!
