### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#256]
"Replaced custom Base64 class with commons-codec implementation" made the library not working anymore on Android (if using CAP/SASL), due to Android having its own old version of commons-codec.
Can you replace it with a shaded version?

**Comment by TheLQ** [comment]
I think I've fixed this in b6d353886b by using encodeBase64(byte[]) which is available in commons-codec 1.3 (the version the android framework uses) according to this: http://javadox.com/commons-codec/commons-codec/1.3/org/apache/commons/codec/binary/Base64.html

If you update your snapshot, does it work?

**Comment by MyWay** [comment]
Yes, with the snapshot it's working.

**Comment by MyWay** [comment]
Anyway I'm getting this (on freenode):
ERROR PircBotX - Exception encountered when parsing line :asimov.freenode.net CAP Mynickname ACK :sasl
System.out﹕ java.lang.UnsupportedOperationException: null
at org.pircbotx.InputParser.processConnect(InputParser.java:460)

It seems this happen only if I set .setCapEnabled(true), but anyway sasl isn't working. It seems that one problem is you're using bot.getEnabledCapabilities().addAll(capParams);, but bot.getEnabledCapabilities() is immutable.

**Comment by TheLQ** [comment]
These issues should all be resolved
