### ISSUE TITLE
Own messages vs other message?

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#258]
Why MessageEvent, ActionEvent and so on aren't fired for own messages? And how is it supposed to get own messages? Thank you.

**Comment by TheLQ** [comment]
The server doesn't send your own lines back to you, its assumed that not returning an error = success. Output parsing though is planed for 2.2 in Issue #215. 

Would an event containing the raw line that was sent to the server be useful?

**Comment by MyWay** [comment]
Output parsing would be nice. In my opinion it would be convenient to have something like OutputMessageEvent and OutputPrivateMessageEvent, as for the rest raw lines should suffice.

**Comment by TheLQ** [comment]
Closed as OutputEvent already covers raw lines and output parsing is in #215
