### ISSUE TITLE
Generic <T extends PircBotX> T getBot() for UserHostmask and Channel

### ISSUE THREAD

**Issue by Shockah** [pircbotx/pircbotx#261]
For some time now Events use a generic version of the getBot method, simplifying the code (developers don't need to cast the bot instance if they're extending the PircBotX class). I think the same thing should be allowed in the User (so UserHostmask) and Channel classes, possibly others too.

**Comment by TheLQ** [comment]
Yes, that makes sense. All the getBot methods should be added everywhere in 0649e9b
