### ISSUE TITLE
Twitch: onNotice() no timeout Notice?

### ISSUE THREAD

**Issue by Gurkengewuerz** [pircbotx/pircbotx#262]
Hey,
how can i get the notice like "xyz has been timed out." or "xyz just subscribed"?
In my opinion these are onNotice events ^^

-Thanks, greetings from Germany

**Comment by SSederberg** [comment]
@Gurken2108 those kind of events are related to the [Twitch API](https://github.com/justintv/Twitch-API). however, there seems to be a way of doing what your asking via a Message or maybe a ActionEvent. [Here's something to help you in your direction](https://github.com/Gocnak/Botnak/blob/b21d075e61f6e203d01bc04cf615c3322e252046/src/main/java/irc/IRCViewer.java#L97). It uses the PircBot library, but it's close enough to get started.

**Comment by Gurkengewuerz** [comment]
Yeah, Thanks. Got it! keyword is: "CAP REQ :twitch.tv/tags"
