### ISSUE TITLE
Twtich: Can't Send Private Message

### ISSUE THREAD

**Issue by Gurkengewuerz** [pircbotx/pircbotx#263]
Hey,

I tried to send a private message ( "sendMessage("Gurkengewuerz", "Bla bla bla bla");" ). If i watch in the Channel, there is no message.

-Greetings from Germany

**Comment by Gurkengewuerz** [comment]
After a bit of googeling you can send Private messages after connect to the "group chat servers". Now my question is, how to do this in the PircBot

**Comment by SSederberg** [comment]
Twitch's IRC system doesn't function like most IRC networks. To send a private message to a user on Twitch you have to do the following: /w username message

**Comment by Gurkengewuerz** [comment]
@AnUnknownMiner Nope, you must first connect to the "Group Chat Servers", but i cant get it to work!

**Comment by Gurkengewuerz** [comment]
@AnUnknownMiner Got it! We can share our ideas via Skype if u want ;)

**Comment by SSederberg** [comment]
I'm not interested, but I think sharing how you did it would help other people with this problem in the future, and we could just mention this issue and close future issues. :+1:

**Comment by Gurkengewuerz** [comment]
You must connect to: "199.9.253.119:6667, username, oAuthKey" with second IRCBot. After Joining you must send a RawMessage: "CAP REQ :twitch.tv/commands". Now you can Recive WHISPER messages.
