### ISSUE TITLE
JoinEvent not firing when bot enters a channel?

### ISSUE THREAD

**Issue by SSederberg** [pircbotx/pircbotx#264]
I'm making a bot for Twitch, and when it's supposed to join a channel, it will print to the console that a timer has started and will execute the rest of the code, but it doesn't print anything to the console upon joining and the code doesn't run.

I believe that this is a bug within the API, and just wanted to see if anyone else is having that problem.

**Comment by Gurkengewuerz** [comment]
Yeah, too

**Comment by AnUnknownMiner** [comment]
[[selfie-placeholder-1]]

[[selfie-placeholder-2]]

**Comment by SSederberg** [comment]
Didn't mean to do that...

**Comment by TheLQ** [comment]
Works on my end (the o.p.impl.SandboxBot:onJoin line), are you sure you added your listener in the configuration?

```
o.p.output.OutputRaw:rawLine - JOIN #girlstorule  
o.p.InputParser:handleLine - :tmi.twitch.tv 002 thereallq :Your host is tmi.twitch.tv 
o.p.InputParser:handleLine - :tmi.twitch.tv 003 thereallq :This server is rather new 
o.p.InputParser:handleLine - :tmi.twitch.tv 004 thereallq :- 
o.p.InputParser:handleLine - :tmi.twitch.tv 375 thereallq :- 
o.p.InputParser:handleLine - :tmi.twitch.tv 372 thereallq :You are in a maze of twisty passages, all alike. 
o.p.InputParser:handleLine - :tmi.twitch.tv 376 thereallq :> 
o.p.InputParser:handleLine - :thereallq!thereallq@thereallq.tmi.twitch.tv JOIN #girlstorule 
o.p.output.OutputRaw:rawLine - WHO #girlstorule 
o.p.output.OutputRaw:rawLine - MODE #girlstorule 
o.p.UserHostmask:updateHostmask - Updating hostname to thereallq.tmi.twitch.tv for user Thereallq!PircBotX@null 
o.p.UserHostmask:updateHostmask - Updating login to thereallq for user Thereallq!PircBotX@thereallq.tmi.twitch.tv 
o.p.impl.SandboxBot:onJoin - Channel join JoinEvent(channel=Channel(name=#girlstorule, channelId=4d7cbcca-2471-4d80-85bf-bf53fc0b797b, bot=.., output=org.pircbotx.Channel$1@68be2bc2, mode=, topic=, topicTimestamp=0, createTimestamp=0, topicSetter=null, moderated=false, noExternalMessages=false, inviteOnly=false, secret=false, channelPrivate=false, topicProtection=false, channelLimit=-1, channelKey=null, modeChangeLatch=null, modeChangeLock=java.lang.Object@28feb3fa), user=User(super=UserHostmask(extbanPrefix=null, nick=Thereallq, login=thereallq, hostname=thereallq.tmi.twitch.tv), userId=c103506f-4e60-4fd0-a88b-025e055bc90e, realName=, awayMessage=null, ircop=false, server=, hops=0), userHostmask=UserHostmask(extbanPrefix=null, nick=thereallq, login=thereallq, hostname=thereallq.tmi.twitch.tv)) 
o.p.InputParser:handleLine - :thereallq.tmi.twitch.tv 353 thereallq = #girlstorule :thereallq 
o.p.InputParser:handleLine - :thereallq.tmi.twitch.tv 366 thereallq #girlstorule :End of /NAMES list 
o.p.InputParser:handleLine - :tmi.twitch.tv 421 thereallq WHO :Unknown command 
o.p.InputParser:handleLine - :ninjacon!ninjacon@ninjacon.tmi.twitch.tv PRIVMSG #girlstorule :Алин, ты любишь шарики? 
```

**Comment by SSederberg** [comment]
I do not get that line, and my JoinEvent class is in the configuration. [Here is the class in question](https://gist.github.com/AnUnknownMiner/e6fcc229d3a3a9a703c4), sorry if the format is bad.

**Comment by TheLQ** [comment]
If you can't see that "has joined the channel" log its hard to say without seeing the configuration and a log. 

You also seem to be running an old version as your still using <PircBotX> generics. 2.1 does have some bugfixes for twitch and I've just made a [Twitch.tv support wiki page](https://github.com/TheLQ/pircbotx/wiki/Twitch.tv-support). This makes it even harder to say where the issue is coming from. 

Can you try the [latest snapshot](https://github.com/TheLQ/pircbotx/wiki/DevVersion)?

**Comment by SSederberg** [comment]
I will try the latest snapshot and report what I get.

**Comment by SSederberg** [comment]
I still get nothing, here is the [Configuration and console output on startup](https://gist.github.com/AnUnknownMiner/633429a763241ac29818).

**Comment by SSederberg** [comment]
So JoinEvent is working again. I don't know why it stopped, but the code within the timer is executing.
