### ISSUE TITLE
Channel message sent as Private message

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#267]
It seems that sometimes channel messages are received as if they are private messages. Any idea? I will try to look further into while waiting.

**Comment by TheLQ** [comment]
I'm not sure how that would be possible, a channel message is a channel message. Can you post a log?

**Comment by MyWay** [comment]
Yes, I confirm that when this happens you get the channel message as a PrivateMessageEvent. I can't still reproduce it everytime.

**Comment by MyWay** [comment]
Here is a one line log:
[Thread-182] INFO  InputParser - :VeNeRe!~VeNeRe@unaffiliated/myway/bot/castigo PRIVMSG #ChatGratis :Message
So probably the problem is inside the InputerParser?

**Comment by MyWay** [comment]
Ok, it's not the autoreconnection.
Maybe it's setAutoNickChange(true), if you connect with a nickname already in use and you get a 433, but it's not happening every time.

**Comment by TheLQ** [comment]
The only time you'll get a channel message as a private message is if the channel doesn't exist in the UserChannelDao for some reason. I'll admit the parser could be better but that should be fixed in 2.2

I'm not sure how this is related to auto nick change, but that's fixed in #269.
