### ISSUE TITLE
Issue: DCC from User with IPv6

### ISSUE THREAD

**Issue by darkmain** [pircbotx/pircbotx#268]
When I try to download from a User with an IPv6 address, I got this error: "java.net.ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine".

I found out that the problem occurs during the accept process.
The function acceptFileTransfer() in the DccHandler class tries to set the local ip address in usersocket with getRealDccAddress(). But it always returns an IPv4 address.

If I set the local ip address in usersocket null. I got no problems because then I have an IPv6 address.

The Server itself uses IPv4.

**Comment by TheLQ** [comment]
I believe the latest snapshot ( https://github.com/TheLQ/pircbotx/wiki/DevVersion ) should temporarily fix this issue. Let me know if it fixes the issue for you, I'm not setup for IPv6 to test this

Long term I'll probably have to add stack-specific setters, eg setV4LocalAddress and setV6LocalAddress. But that's tricky to handle correctly (and test)

**Comment by darkmain** [comment]
I tested it. Its working now. Thanks.
