### ISSUE TITLE
NickAlreadyInUse and AutoChange

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#269]
I think that on RAW 433 you should add a check on the nick:
433 \* Bigfoot :Nickname is already in use.
433 Bigfoot` Bigfoot :Nickname is already in use.
While the first line is saying that your current nick is in use, the second is not, but you change the nickname anyway, if autochange is true!

**Comment by TheLQ** [comment]
So if I'm understanding you correctly the auto nick change function was running anytime the nick was already in use, even long after connecting to the server when you did the nick change yourself. This should be fixed in 7d32bd8
