### ISSUE TITLE
Unknown Channel Mode Parameters mess up other known mode parameters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#27]
```
I was going to document this issue on a "Known unfixable issues" wiki page, but 
I'll ask here for any advice

In cases where a channel mode is set and one of the modes is unknown its 
possible for PircBotX to report the wrong information.

Consider this mode change on the Freenode IRC Network

{{{
MODE #quackbot +fk #quackbot2 test
}}}

To freenode, this means setup channel forwarding to #quackbot2 and to set the 
channel key to test. However PircBotX doesn't support the channel forwarding 
mode. The result of this is a SetChannelKeyEvent with a key of "#quackbot2", 
which is wrong.

Can anyone think of a way to fix this?
```

Original issue reported on code.google.com by `Lord.Qua...@gmail.com` on 18 Jun 2011 at 4:11
- Blocking: #28

**Comment by jztech101** [comment]
I don't see any possible fix. And in fact, if you consider this further, different channel modes do different things on different IRCds. You would have to check the IRCd before determining with channel mode is being set. It ultimately just makes the situation all the more confusing. My recommendation is simply make this a ChannelModeEvent and have the developer parse the ChannelModes based on the IRCd they wish to support.

**Comment by hoerup** [comment]
Since Pircbotx 2.1 sends specialized mode events for those it knows + a generic modevent and everything else is a only generic ModeEvent - i don't think there's much more that can be done.
