### ISSUE TITLE
jitpack build issue

### ISSUE THREAD

**Issue by ysangkok** [pircbotx/pircbotx#276]
see https://jitpack.io/com/github/TheLQ/pircbotx/-latest-g95bf8b0-441/build.log

**Comment by TheLQ** [comment]
> Unknown host repo.maven.apache.org: unknown error

Seems like a DNS or mirror issue. Can you open this link in your browser: http://repo.maven.apache.org/maven2/org/pircbotx/pircbotx ?

**Comment by ysangkok** [comment]
I can open it just fine, but Jitpack can't for some reason. Could be a problem with Jitpack, but that would be surprising.

**Comment by TheLQ** [comment]
It's on their end, if they can't get to maven central then there's nothing I can do. It might be a temporary issue with their mirror or network. FWIW the Travis build passes: https://travis-ci.org/TheLQ/pircbotx and I can build a fresh clone on my machine.
