### ISSUE TITLE
[feature req.] KillEvent

### ISSUE THREAD

**Issue by Diagamma** [pircbotx/pircbotx#278]
I think a KillEvent (https://tools.ietf.org/html/rfc1459#section-4.6.1) would be useful. ^^

**Comment by hoerup** [comment]
There is no such thing as a KillEvent - a kill is a special instance of a Quit - but you can listen for QuitEvents and parse if quitmessage contains "Killed" - otherwise you can listen for SNOMASK if the irc server supports this

**Comment by Diagamma** [comment]
Okay, thanks. :D

**Comment by hoerup** [comment]
@TheLQ speaking of SNOMASK notices - do you know how to intercept these ?
