### ISSUE TITLE
Error while trying to get the Userlist

### ISSUE THREAD

**Issue by MrBoulet** [pircbotx/pircbotx#283]
Hello, sorry for my english this is not my native language.

Here is my code : 

```
package bot;
import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.hooks.ListenerAdapter;

public class bibot extends ListenerAdapter {

    @SuppressWarnings({ "unchecked", "rawtypes" })
    public static void main(String[] args) throws Exception {
            //Configure le Bot
            Configuration configuration = new Configuration.Builder()
                            .setName("BouyashakaB") //Pseudo
                            .setServerHostname("irc.twitch.tv") //Twitch IRC
                            .setServerPassword("oauth:***************************") //MDP
                            .addAutoJoinChannel("#Blbla") // Channel
                            .addListener(new bibot()) // On ecoute
                            .buildConfiguration();

            //Create our bot with the configuration
            PircBotX bot = new PircBotX(configuration);
            //Connect to the server
            bot.startBot();
    }
}
```

I would like to put the name of all users of my channel in to an array.
But I first tried to print the user list in my bash.
# FirstTry

```
@Override
public void onJoin(JoinEvent event) throws Exception {
    event.getBot().waitFor(UserListEvent.class);
    System.out.println(event.getChannel().getUsers());
}
```

The error is on the "waitFor", so I tried to import org.pircbotx.hooks.WaitForQueue;
Didn't change anything.
# SecondTry

```
        @Override
    public void onUserList(UserListEvent event) {
        System.out.println("BLBLABLBLABLABLABLABLABLABLABLA");
    }
```

The "BLBLABLA...." never came.

What should I do ?

Hope someone can help me.

**Comment by lilggamegenius** [comment]
if you want to get the user list you have to do something like this

``` java
Iterator<User> user = event.getChannel().getUsers().iterator();
List<String> userList = new ArrayList<>();
while(user.hasNext()){
    userList.add(user.next().getNick());
    }
```

Although this results in a List you can simply use the .toArray() method to get a normal array

**Comment by hoerup** [comment]
in pircbotx 2.1 you can just:
	@Override
	public void onUserList(UserListEvent event) throws Exception {
		for (User u : event.getUsers()) {
			System.out.println(u.getNick());
		}
	}

**Comment by lilggamegenius** [comment]
Oh, I just noticed this was Twitch and not normal IRC.
Twitch does not send userlists. Instead, you have to wait for it to send a join for every user at once.
Twitch by default doesn't send JOIN, PART, and NAMES unless you request it, see https://github.com/justintv/Twitch-API/blob/master/IRC.md#membership
With PircBotX you can request it by adding this to your config
```java
.setCapEnabled(true)
.addCapHandler(new EnableCapHandler("twitch.tv/membership"))
```
You should add this as well since Twitch doesn't support it
```java
.setAutoNickChange(false)
.setOnJoinWhoEnabled(false)
```

I also add these but you shouldn't need them
```java
.addCapHandler(new EnableCapHandler("twitch.tv/commands"))
.addCapHandler(new EnableCapHandler("twitch.tv/tags"))
```
