### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#286]
[Thread-161] ERROR PircBotX - Exception encountered during connect
I/System.out: javax.net.ssl.SSLHandshakeException: Handshake failed
I/System.out:   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396) ~[na:0.0]
I/System.out:   at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629) ~[na:0.0]
I/System.out:   at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591) ~[na:0.0]
I/System.out:   at org.pircbotx.PircBotX.changeSocket(PircBotX.java:345) ~[na:0.0]
I/System.out:   at org.pircbotx.PircBotX.connect(PircBotX.java:313) ~[na:0.0]
I/System.out:   at org.pircbotx.PircBotX.startBot(PircBotX.java:188) ~[na:0.0]
I/System.out: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x9f3b73c0: Failure in SSL library, usually a protocol error
I/System.out: error:100bd10c:SSL routines:ssl3_get_record:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/s3_pkt.c:311 0xab254d97:0x00000000)
I/System.out:   at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
I/System.out:   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324) ~[na:0.0]

Any idea why is this happening on Android (I'm testing on 6, but it seems it's happening at least on >= 5)?

**Comment by TheLQ** [comment]
What server is this? Googling "java ssl3_get_record:WRONG_VERSION_NUMBER" pulls up several results about the server using older SSLv3 instead of TLS.

**Comment by MyWay** [comment]
It's CentOS 6.6 with Unrealircd 3.2.10.6. So it could be due to the OpenSSL version?

**Comment by TheLQ** [comment]
Probably. It looks like Unreal 3.2.x was deprecated though in favor of Unreal 4: https://forums.unrealircd.org/viewtopic.php?t=8436

As long as your on the latest PircBotX (try the snapshot too: https://github.com/TheLQ/pircbotx/wiki/DevVersion ) this isn't really a PircBotX issue as it just uses the built in TLS handling. If you find any solutions that say to do stuff to the SSLSocket, you can put that in a SocketFactory and pass it to configBuilder.setSocketFactory(), then PircBotX will use it when connecting.
