### ISSUE TITLE
getRecipientHostmask() is null in KickEvent

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#293]
SomeoneWhoPrefersToHaveAPrivateNickForWhateverReason_ (null@null). https://github.com/TechCavern/WaveTact/blob/master/src/main/java/com/techcavern/wavetact/eventListeners/KickListener.java#L26

**Comment by hoerup** [comment]
I can't reproduce this. Please provide more details (which network - ircd edition+version etc)

**Comment by lilggamegenius** [comment]
Can nicks even be that long?

**Comment by hoerup** [comment]
@lilggamegenuis  Most networks doesn't allow that long - but eg. inspircd states the length *could* go up to 500 even though they dont recommend going over the defaults
https://wiki.inspircd.org/Configuration#.3Climits.3E

**Comment by jztech101** [comment]
@hoerup This was so long ago, that I've honestly forgotten. Thatbeing said, I can almost gurantee it has more to do with Private nicks than Nick length. I just don't remember what private nicks even is right at this moment.
