### ISSUE TITLE
Document how to make PircBotX join a channel on runtime

### ISSUE THREAD

**Issue by m-gora** [pircbotx/pircbotx#297]
Hi,

i want to make PircBotX join a channel during the runtime. I haven't found anything to make that happen. I crawled the web, the docs and even the closed issues. 

Is it even possbile with PircBotX? Pircbot seems to be able to join channels during the runtime.

**Comment by TheLQ** [comment]
This should probably be covered on the docs:

bot.send().joinChannel("#someChannel")

**Comment by m-gora** [comment]
Hey,

thanks for your reply. It's not covered in the Wiki here on Github. Same with leave channel. 
Doesnt seem to work the same way like join channel.

I searched through the whole code, it seems that there is no method that sends a PART request.
so i'm just gonna send it raw for now.

**Comment by Shockah** [comment]
@blackanthrax Uhhh...  
https://github.com/TheLQ/pircbotx/blob/master/src/main/java/org/pircbotx/output/OutputChannel.java#L45

**Comment by lpreams** [comment]
It's not exactly well documented. I read the wiki and spent a bit digging through the javadoc, and eventually had to resort to Googling for a solution, which lead me to this page. Also, I'd like to note that if you are trying to join a channel in response to an event, you should use 

`event.getBot().send().joinChannel("#someChannel")`

**Comment by hoerup** [comment]
I think the docs are clear enough - if you have enhancements to them please open a PR

**Comment by hasandiwan** [comment]
I added a method to OutputIRC.java called partChannel as [pull request 420](https://github.com/pircbotx/pircbotx/pull/420)
