### ISSUE TITLE
Android NoClassDefFoundError org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#298]
java.lang.ExceptionInInitializerError at org.pircbotx.Configuration$Builder.<init>(Configuration.java:515)
Caused by: java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory
at org.pircbotx.cap.EnableCapHandler.<clinit>(EnableCapHandler.java:34)
at org.pircbotx.Configuration$Builder.<init>(Configuration.java:515)

**Comment by TheLQ** [comment]
Is slf4j on your classpath?

**Comment by MyWay** [comment]
I'm using compile 'org.slf4j:slf4j-api:1.7.+', on Gradle, so yes. It seems it's crashing on Android 4 only, anyway.
If I change it to compile 'org.slf4j:slf4j-api:1.7.13', which seems the version needed by pircbotx, the same happens.
If I change it to compile 'org.slf4j:slf4j-android:1.7.+', I get duplicate entry: org/slf4j/impl/StaticLoggerBinder.class when building.

**Comment by MyWay** [comment]
My error, I've found the solution here if somebody else needs it: http://stackoverflow.com/questions/27698287/noclassdeffounderror-with-android-studio-on-android-4
I had to extend MultiDexApplication after changing to multidex.
