### ISSUE TITLE
Several events fail to preserve IRCv3 tags

### ISSUE THREAD

**Issue by skyboy** [pircbotx/pircbotx#299]
Several events, notably `ActionEvent` and its related CTCP events, dump the IRCv3 tag map into the ether instead of preserving them into user code, making handling those events when data in the tags is required or desired nigh impossible.

**Comment by aerinnight** [comment]
Twitch.TV's IRCv3-based chat server, in particular, sends IRCv3 tags along with `ActionEvent` and `NoticeEvent` for sure, and maybe others.  Is there a reason Tag support is limited to `MessageEvent` and not all Events that implement, say, `GenericMessageEvent`?

The `handleLine(~)` call in `InputParser.java` seems to attempt to extract the tags anyway regardless of the event type, should be easy to add to more events wherever needed.

**Comment by hoerup** [comment]
@AerinNight 's PR is merged
