### ISSUE TITLE
wrong order of UserLevels

### ISSUE THREAD

**Issue by Pupskuchen** [pircbotx/pircbotx#301]
Hi,
the order of user levels (in enum UserLevel) doesn't really seem to make sense, AFAIK op is more powerful than HOP, right?
The order was changed before: https://github.com/TheLQ/pircbotx/commit/983c69022ebaf4784cf70d29e15062391a8f313d - but now OP and HALFOP need to be swapped in order to make comparing easier and nicer.

**Comment by R3ido101** [comment]
@Pupskuchen I agree

**Comment by MyWay** [comment]
I agree.

**Comment by hoerup** [comment]
Fixed by TheLQ in 6e53cdff8126290e1751c77d9dff569f7f0792db
