### ISSUE TITLE
endless recursion in ActionEvent.respond

### ISSUE THREAD

**Issue by Pupskuchen** [pircbotx/pircbotx#303]
I don't know whether this is done on purpose or not, but the respond-method of ActionEvent does nothing but calling itself (which makes it pretty useless): https://github.com/TheLQ/pircbotx/blob/master/src/main/java/org/pircbotx/hooks/events/ActionEvent.java#L106

Also, getMessage and getAction do the same thing, why do they **both** exist?

Is this a bug or am I just not able to understand how it's supposed to work?

**Comment by hoerup** [comment]
Fixed in git HEAD
