### ISSUE TITLE
UserLevel order

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#307]
VOICE("+"),
    **OP("@"),**
    **HALFOP("%"),**
    SUPEROP("&"),
    OWNER("~");

**should be:**
VOICE("+"),
    **HALFOP("%"),**
    **OP("@"),**
    SUPEROP("&"),
    OWNER("~");

**Comment by lilggamegenius** [comment]
I agree but this was already added to the issues here #301
