### ISSUE TITLE
Problems joining freenode?

### ISSUE THREAD

**Issue by ghost** [pircbotx/pircbotx#310]
For some reason I can't get my bot to join freenode irc but I can get it to join efnet... What's wrong with my code?

public static void main(String[] args) throws Exception {
        Configuration configuration = new Configuration.Builder().setName("V0idBot").addAutoJoinChannel("#v0idbottest").addServer("irc.freenode.net").addListener(new MyListener()).buildConfiguration();
        PircBotX bot = new PircBotX(configuration);
        bot.startBot();
    }

**Comment by TheEpTic** [comment]
It seems like an issue of Freenode's end.
Can you verify the connection the bot is running on can connect to Freenode too?
Also, when you say it can't join, what error do you get? Is it a timeout error?
A bit more information would be awesome to help debug this issue for you! :+1: :)

**Comment by TheLQ** [comment]
That configuration works for me and I can join the channel. Can you post the log? It's hard to tell what happened without it

**Comment by hoerup** [comment]
This is quite old. I assume you have found a solution. If not, feel free to re-open the issue.
