### ISSUE TITLE
Maybe a Configuration.Builder option for system output

### ISSUE THREAD

**Issue by TheEpTic** [pircbotx/pircbotx#311]
So, I've been using the bot quite a bit recently and must say I love it!

The one thing I do find annoying mostly is that I can't find any way to turn off the system.out it does for every IRC event.

I want to turn this off so I can make up multiple event catchers and have a nice clean output rather than it being flooded with what users say.

Opinions?

**Comment by bl4ckscor3** [comment]
In my bot I [disabled all loggers](https://github.com/bl4ckscor3/bl4ckb0t/blob/master/src/bl4ckscor3/bot/bl4ckb0t/Core.java#L26) and [modified slf4j's source code](https://github.com/bl4ckscor3/bl4ckb0t/tree/master/src/org/slf4j/impl) to just log errors. (If you use this modification make sure to go through the code and delete any lines that you don't want which I included, I did that to adapt the code specifically to my bot. All of these lines should be commented by me.) I then set up [this class](https://github.com/bl4ckscor3/bl4ckb0t/blob/master/src/bl4ckscor3/bot/bl4ckb0t/logging/Logging.java) with all the events and logging I need. If you want, you can just take this class, give me credit and edit it as you want.

Logging excerpt:

> Started logging on Sun Mar 20 23:22:16 CET 2016
> Sun Mar 20 23:22:16 CET 2016 [INFO] Created new file to copy to: "bl4ckb0t - Sun Mar 20 23-22-16 CET 2016.log"
> Sun Mar 20 23:22:16 CET 2016 [INFO] Starting copy process...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Successfully copied old logging file.
> Sun Mar 20 23:22:16 CET 2016 [INFO] Disabled loggers...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Bot was started as WIP version...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Checking for custom config file...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Custom config file already existed...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Config values successfully written into memory, checking for new values to add...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Restored values that got reset during any possible config additions...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Configuration setup complete!
> Sun Mar 20 23:22:16 CET 2016 [INFO] Created PircBotX config...
> Sun Mar 20 23:22:16 CET 2016 [INFO] Cleared all lists...
> Sun Mar 20 23:22:17 CET 2016 [INFO] All versions added to changelog list.
> Sun Mar 20 23:22:37 CET 2016 [MESSAGE] #bl4ckb0tTest | bl4ckscor3: testmessage

**Comment by TheEpTic** [comment]
Nice! I still think it would benefit many people if they made an off switch but I guess that works ;)

**Comment by bl4ckscor3** [comment]
Yes, it took quite some time to get it working how it is now, so a hook or something to add a custom logger would be benefical!

**Comment by TheLQ** [comment]
Set the log level of org.pircbotx.hooks.managers.ThreadedListenerManager (or whatever listenermanager your using) to INFO in your logging system. The "Received Event" line is at DEBUG so won't be shown

Setting the root logger to OFF disables all logging everywhere, which unless you want to do that for some reason isn't necessary. 

Can you try Logger.getLogger("org.pircbotx.hooks.managers.ThreadedListenerManager ").setLevel(Level.INFO); ?

**Comment by TheEpTic** [comment]
That did nothing sadly. :(

**Comment by hoerup** [comment]
As TheLQ stated - its controlled by SFL4J. I assume you have found a fix for it now. If not please re-open this issue.
