### ISSUE TITLE
UserChannelDao: UnknownUser when bot in >1 channels

### ISSUE THREAD

**Issue by jopek** [pircbotx/pircbotx#313]
## Steps to reproduce:
- join network and channel (irc.abjects.net / #moviegods)
- make same bot join another channel (#mg-chat)
- wait for a user to part the channel

[code to reproduce](https://github.com/jopek/multichannel_pircbotx_bug/blob/master/src/main/java/MultiChannel.java) - turns out, the listener isn't even required to reproduce the error.
[sample run with typical exception thrown](https://gist.github.com/jopek/4937623041e06ee4efa5e0df2524794f)

Quite possibly a duplicate of [issue 148](https://github.com/TheLQ/pircbotx/issues/148). The Issue was fixed, yet I still get the `org.pircbotx.exception.DaoException: UnknownUser: ...`

**Comment by hoerup** [comment]
That network  returns some non standard hostmasks - but to strenghen it UserHostMask constructor could verify that hostmaskParts is 3 elements long
