### ISSUE TITLE
Socket timeout not respected

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#315]
I'm setting the connection timeout with setSocketTimeout(30000), but it seems it's still waiting for about 5 minutes. To test it, I've blocked my ircd port with the firewall. How can I lower the timeout? Thanks.

**Comment by asgs** [comment]
As far as I know, the Configuration class doesn't have a setter for that property. Can you post a snippet as to how you're doing it at the moment?

**Comment by MyWay** [comment]
`Configuration.Builder mConfiguration = new Configuration.Builder()
.setSocketTimeout(30000)`

**Comment by hoerup** [comment]
TheLQ has fixed this in on master branch - part of 2.2 snapshot
