### ISSUE TITLE
Background Colors

### ISSUE THREAD

**Issue by Yuuki2012** [pircbotx/pircbotx#316]
Pls add background colors

**Comment by lilggamegenius** [comment]
you can easily add background colors by concatenating a color, the string ",", and another color
for example: Color.RED + "," + Color.Blue
the class names might not be exactly right but that's the basic idea

**Comment by Yuuki2012** [comment]
> _> oh well, not what I wanted.

**Comment by bl4ckscor3** [comment]
You can use this method I wrote for my own bot.
https://github.com/bl4ckscor3/bl4ckb0t/blob/master/src/bl4ckscor3/bot/bl4ckb0t/util/Utilities.java#L344

**Comment by Yuuki2012** [comment]
Well thx, I added in it in Colors.java (also switched String background, String foreground -> String foreground, String background), and recompiled pircbotx, now it works fine =^_^=

Unrelated: Why is it that I can't use Maven on Windows but I can on Linux? (using the exact same commands), it says something about missing plugins.

**Comment by TheLQ** [comment]
While simply joining with "," is shorter, this has been requested before so I've added Colors.bg and Colors.set

It should work on Windows, make another issue with the exception if it still doesn't work
