### ISSUE TITLE
Update Maven Wiki

### ISSUE THREAD

**Issue by C3realGuy** [pircbotx/pircbotx#320]
`<version>2.1-SNAPSHOT</version>` is not available anymore, `version>2.1.1-SNAPSHOT</version>` should be the thing. Or maybe even 2.2-SNAPSHOT.

https://github.com/TheLQ/pircbotx/wiki/DevVersion

**Comment by wlami** [comment]
After checking out and successfully building locally I updated the wiki to 2.2-SNAPSHOT.
