### ISSUE TITLE
Version 2.1 dependency not available through Maven

### ISSUE THREAD

**Issue by bholagabbar** [pircbotx/pircbotx#323]
I built a bot yesterday and tested it on the channel. Works great. However, I had to add the 2.0.1 version dependency. Maven couldn't find 2.1

I'll post my current pom file here. Try changing 2.0.1 to 2.1 and do tell me if it works:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.shreyans-sheth</groupId>
    <artifactId>irackbot</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>irackbot</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.pircbotx</groupId>
            <artifactId>pircbotx</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.21</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>me.irackbot.MyListener</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by tobciu** [comment]
Hey, i've not tested your pom but it should be available through maven http://mvnrepository.com/artifact/org.pircbotx/pircbotx/2.1
Can you provide the output from a build?

**Comment by bholagabbar** [comment]
I don't think the output from a maven build would help because it won't build in the first place. 2.1 shows an error in the pom file in my idea itself. It refuses to download the dependencies. I'll attach a picture showing the same.

![screenshot from 2016-08-28 15-46-05](https://cloud.githubusercontent.com/assets/11693595/18033058/94a99730-6d36-11e6-99ff-2b7ac2880087.png)

If you wish to test out the same (I hope you do), check out the source code here. Simply import it in your IDE as a maven project and change 2.0.1 to 2.1. See if it works. https://github.com/bholagabbar/iRack

**Comment by bholagabbar** [comment]
@TheLQ @tobciu Could you look into this?

**Comment by tobciu** [comment]
is this still actual? i forgot this issue, sorry... 
but i've tested your code and it works fine for me... do you have a customized settings.xml in your home directory? see https://maven.apache.org/settings.html

**Comment by bholagabbar** [comment]
Really strange as to why it didn't work for me. I had to rewrite my code
using the older pircbot library :( There's not one easy way mentioned in
docs to simply send a message over IRC. I created an issue and the reply
was a little late. Maybe we can add that in the docs? I completed my
project and it's now officially listed on Slack tho!

**Comment by s5bug** [comment]
Import the dependency using JitPack. [jitpack.io](jitpack.io)

**Comment by hoerup** [comment]
PircbotX 2.1 is available through maven central as tobciu stated
