### ISSUE TITLE
(Question)  Straightforward method to simply send a message incase of no event?

### ISSUE THREAD

**Issue by bholagabbar** [pircbotx/pircbotx#324]
I found no way of simple sending a message, say "Hello world" to the channel. I simply just want to send it. It isn't an event or anything of that sort. There seems to be no example in the documentation too. Could anyone tell me how I could do that?

**Comment by bl4ckscor3** [comment]
You can use your PircBotX instance to send a message via instance.sendIRC().message("#channel" "Hello world");

**Comment by bholagabbar** [comment]
Thank you so much. This really ought to be in the documentation man.
