### ISSUE TITLE
java.net independence

### ISSUE THREAD

**Issue by SoniEx2** [pircbotx/pircbotx#327]
Can you rewrite parts of the bot so it can work when only [these classes](https://github.com/SoniEx2/Terasology/blob/internet/engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java) are available?

**Comment by Cypherke** [comment]
which are in use by the bot that are not on the list? Also... why...

**Comment by SoniEx2** [comment]
java.net.Socket?

Benefits:

1. Bot over netty.
2. Bot over websockets.
3. Bot in sandboxed environments.
4. Bot over i2p.
5. Etc.

**Comment by Cypherke** [comment]
that would be alot of work :)

**Comment by SoniEx2** [comment]
Probably not. I took a quick look at the code and it might be easier than you think.

**Comment by Cypherke** [comment]
feel free to submit a PR then

**Comment by hoerup** [comment]
Please open a PR with the reduced dependencies, if you still need this
