### ISSUE TITLE
Disconnection on Android When Switching Networks

### ISSUE THREAD

**Issue by ryan-clancy** [pircbotx/pircbotx#332]
When switching networks on Android (wifi to data, data to wifi, or moving between cell towers) the connection to the IRC server seems to disconnect.

Is there any way to avoid this issue other than to re-connect to the server?

**Comment by lilggamegenius** [comment]
I don't think this is possible since when you switch connections, your IP Address changes (And with 
wifi <--> data, the MAC Address changes too) which means the packets aren't getting sent to a network you're on anymore.

**Comment by hoerup** [comment]
no - there's no way to keep the tcp connection open when switching IP's.

 please close this issue
