### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by paxter** [pircbotx/pircbotx#334]
Tried with latest pircbotx version and netbeans with maven. Always get that compiling error:

> --- exec-maven-plugin:1.2.1:exec (default-cli) @ pircbotx ---
Exception in thread "main" java.lang.RuntimeException: Uncompilable source code - Erroneous sym type: org.pircbotx.Configuration.Builder.setName.addServer.addAutoJoinChannel.addListener.buildConfiguration
	at TestBot.main(TestBot.java:37)

**Comment by Cypherke** [comment]
what's on line 37 of you TestBot.java class?

**Comment by paxter** [comment]
There is:

> Configuration configuration = new Configuration.Builder()

I used the exact default code from introduction page there: https://github.com/TheLQ/pircbotx

**Comment by hoerup** [comment]
I suppose it's this one that fails?
                                .addListener(new MyListener()) //Add our listener that will be called on Events

it's up to you to implement your own event listeners and add them to the configuration.

Please close this issue

**Comment by hoerup** [comment]
I assume you have found a solution. If not feel free to re-open this issue.
