### ISSUE TITLE
how can i alter the source?

### ISSUE THREAD

**Issue by JH-Xie** [pircbotx/pircbotx#335]
as i import maven project by intellij IDE by pom.xml in master,i can not compile the peoject and there is error in pom.xml(many plugins can not import),is ther a way i can start the peoject? thanks

**Comment by lilggamegenius** [comment]
If you want to edit the source code, then you should clone the repo.

**Comment by hoerup** [comment]
Your Basic IDE usage can hardly be the responsibility of a library author. Please close this issue.

**Comment by hoerup** [comment]
I assume you have found a solution. If not feel free to re-open this issue.
