### ISSUE TITLE
Problems with sending a message.

### ISSUE THREAD

**Issue by musti645** [pircbotx/pircbotx#336]
Hi folks,
after having trouble with multithreading and PircBot i decided to give your project a try. The integration was not that hard and i thought, i had succeeded, until i started testing out the bot.
The problem is, that i can't, for the love of god, send any messages to the channel, although i receive everything and the MessageEvents fire.
This is the MessageListeners, which extends ListenerAdapter, overridden method (partially of course):
`public void onMessage(MessageEvent event) throws Exception {
            checkCommands(message, userName, event);
    }`

In the methods, where i check if the string equals any of my saved commands, i call the following method:
`    public void sendCommand(String message){
        bot.send().message(channel, message);
    }`

yet nothing happens. I can't figure out why.
Maybe important to note here is, that i am writing a bot for twitch.
I also tried writing rawLines or using the event.respond() method unsuccessfully.

EDIT: While writing this, i let the bot run in the background, making it worksomehow, i don't know how though.  So 10 Minutes after connecting, sending messages works.. Very confusing.

EDIT2: I think this could be a multithreading issue, since i start the bot in a new thread, in order to avoid the "NetworkOnMainThreadException" of Android.

**Comment by hoerup** [comment]
Have you tried implement a onExceptionEvent listener to see if you get any exceptions there ?

**Comment by lpreams** [comment]
I don't see why `bot.send().message()` wouldn't work, but I have found it to be kind of finicky sometimes. I've had much better luck using `event.respond()` or `event.respondWith()`.

**Comment by mechjacktv** [comment]
I am also using `event.respondWith(...)` with great success.

**Comment by hoerup** [comment]
OP didn't return with additional information
