### ISSUE TITLE
Calling send().message("#channel", message) where message has multiple lines causes lines after the first to be run as raw IRC commands.

### ISSUE THREAD

**Issue by fictionbranches** [pircbotx/pircbotx#337]
When calling PircBotX.send().message("#channel", message), if message contains newlines, all lines after the first one are executed as raw IRC commands rather than being sent as part of the message. 

I'm not sure whether the expected behavior should be to ignore text after the first line, or to replace newlines with spaces, or to send each line as a separate message, but it definitely should NOT be to run subsequent lines as raw commands. This behavior isn't mentioned anywhere in the docs that I could find, and could (and in my case did) lead to a pretty huge security flaw in bots. In my case, my bot was acting as a bridge to a discord server. Since discord allows messages to contain multiple lines, and since send().message("#channel", message) will execute commands on lines after the first, my bot was happily executing anything any discord user put on the second line of a message as a raw IRC command, meaning they could make the bot say anything, do anything, join/part any channel, change nick, kick/ban users in channels where the bot has op, etc. 

If this is a feature and not a bug (which I am adamantly against), it should at the very least be mentioned in the docs.

**Comment by lilggamegenius** [comment]
Do you know if this behavior applies if you use a channel object?

**Comment by Cypherke** [comment]
It's a bug. Just tested this and confirmed it, happens on 

- PircBotX.send().message(#channel, message)
- PircBotX.send().message(user, message)
- event.getChannel().send(message)
- event.getUser().send(message)

I'd suggest you sanitize your input @fictionbranches (never trust users!), split on a newline char and send every line individually.

calling @TheLQ how do you see this solved? Just send to the newline or automatically split on newline?

**Comment by hoerup** [comment]
since irc is line oriented i don't think its up to pircbotx to ensure that the input is sanitized - any consumer of a IRC library should know this AND know how to sanitize input

**Comment by hoerup** [comment]
@Cypherke i suggest that we Add a "MultilineInputException extends RuntimeException" and throw that in OutputRaw::sendLine() if the line contains a \n and add a note about it on https://github.com/pircbotx/pircbotx/wiki/Documentation

**Comment by lilggamegenius** [comment]
I think it would be better to, by default, automatically split on newlines and add a config option for it. This way acts similarly to when your line is too long to be sent as one message

**Comment by lpreams** [comment]
I agree, especially since it already splits lines when they're too long. Why should the framework expect users to sanitize input for newlines but for long lines the framework does the sanitization? 

At the very least it should fail (throw some kind of exception) rather than just allow the extra lines to be sent as separate commands. 

And a configuration option would allow a choice between sending each line as a separate message and throwing an exception.
