### ISSUE TITLE
how to connect to Twitch IRC

### ISSUE THREAD

**Issue by HazeTech** [pircbotx/pircbotx#338]
could i get an example of the lines of code you would need to connect to the twitch IRC b/c i cannot get it to connect. Also i cant find any tutorials anywhere on the internet on how to use pircbotx to connect to twitch IRC, i know there is a section here on twitch.tv integration but i cant get it to work, any help would be appreciated.

thanks.

**Comment by hoerup** [comment]
https://github.com/TheLQ/pircbotx/wiki/Twitch.tv-support

**Comment by HazeTech** [comment]
sorry if this is a dumb question, im kinda a noob at programming and to pircbotx, but when it says "//the rest of your config" is there anything else that you would actually need/want for a twitch bot?

**Comment by lilggamegenius** [comment]
The rest is for any other settings you want to change.

**Comment by hoerup** [comment]
@HazeTech 
Yes add any other configuration elements you want (see the options here http://thelq.github.io/pircbotx/latest/apidocs/org/pircbotx/Configuration.Builder.html)

then add your own Listeners

and start the bot

**Comment by hoerup** [comment]
I assume you have found a solution. If not feel free to re-open this issue.
