### ISSUE TITLE
Unable to receive information after reconnection

### ISSUE THREAD

**Issue by greyfreedom** [pircbotx/pircbotx#339]
I use it in my android application and i use a vpn to connect to twitch IRC server. There is no problem with the normal process，but when i disconnect the vpn and wait a minute(about connectAttemptTotal change from i to i+1)，i connect the vpn and i can not receive the message.
But, i disconnect the vpn and connect the vpn in a short period of time(connectAttemptTotal don't change to i+1), I can receive the message.
this is my configuration：

mChatConfiguration = new Configuration.Builder()
                .setName(mName)
                .addServer("irc.chat.twitch.tv")
                .setServerPassword("oauth:" + mAccessToken)
                .addAutoJoinChannel("#" + mChannel)
                .setAutoNickChange(false)
                .setOnJoinWhoEnabled(false)
                .setCapEnabled(true)
                .setAutoReconnect(true)
                .setAutoReconnectAttempts(3600)
                .setAutoReconnectDelay(1000)
                .addCapHandler(new EnableCapHandler("twitch.tv/membership"))
                .addListener(new MyListener())
                .buildConfiguration();
        mBot = new PircBotX(mChatConfiguration);

**Comment by hoerup** [comment]
Have you tried listening for ConnectAttemptFailedEvent() ?

**Comment by hoerup** [comment]
I assume you have found a solution. If not please re-open the issue
