### ISSUE TITLE
Listener exceptions are swallowed

### ISSUE THREAD

**Issue by hoerup** [pircbotx/pircbotx#341]
ThreadedListenerManager.ManagedFutureTask doesn't log or forward exceptions, which means all exceptions from Listeners arent shown or handled.

at a bare minimum it should override setException and log the exception - but preferably Pircbotx should have a exception hook as well

**Comment by Cypherke** [comment]
http://thelq.github.io/pircbotx/latest/apidocs/org/pircbotx/hooks/events/ExceptionEvent.html gets thrown from ListenerAdapter. 
Create an ExceptionListener which implements ListenerAdapter and override the onException function and add it to your ListenerManager.

**Comment by hoerup** [comment]
Of course. Clearly I wasn't awake here - my bad.
