### ISSUE TITLE
Fork of PirctbotX ??

### ISSUE THREAD

**Issue by hoerup** [pircbotx/pircbotx#343]
To all PircbotX users:

I have tried of getting hold on TheLQ / Leon Blakey through various channels - but so far I'm unsuccessful :(

I would really hate it - but it seems like if we want further development on this project - then we will need to fork it. I am willing to do the setup - but are there other contributors that want to join me ?

**Comment by Cypherke** [comment]
I get it, but soon we have 2 forks and neither of them getting updated any more. Don't get me wrong, I 'm all for new updates and patches to this framework as I use it alot. But I'd prefer to keep one repo.

Calling @TheLQ

**Comment by TheLQ** [comment]
If someone is interested in maintaining this I am open to adding them and/or making a Github Organization. That would be better than making PircbotY.

Honestly my day job and other projects have taken up the free time and motivation I had before.

**Comment by hoerup** [comment]
Well if it's ok with you I think the best would be to let it continue under /TheLQ/pircbotx - since thats where all existing links references to. On the other hand it would probably make sense to setup a organisation that's not tied to a individual account??
I am willing to step up as maintainer.

Update: I thought about it a bit - and I think a new github organisation would be the best solution

**Comment by hoerup** [comment]
@TheLQ  i have created a pircbotx github organisation and invited you

**Comment by Cypherke** [comment]
any chance for invites for previous contributors? :D

**Comment by TheLQ** [comment]
Some notes

- Javadocs are still under http://thelq.github.io/pircbotx/latest/project-reports.html , is that going to cleanly migrate? Could I maybe setup something with Jekyll under thelq/thelq.github.io
- pom links need to be updated
- I attempted to keep a mercurial mirror on bitbucket https://bitbucket.org/TheLQ/pircbotx . Unless someone besides me cares I'll put in warnings that the repo is defunct. 
- There is an old travis build config that should be setup again

**Comment by hoerup** [comment]
1. Have no clue if they'll migrate - if not we could set up some new github pages
2. Sure
3. I wasn't aware of the mercurial mirror. But since I havent discovered it, i'll guess that othere people are also unaware - so I would let it go
4. Sure

**Comment by lilggamegenius** [comment]
I'd be willing to contribute. I have a couple of hours of free time a day

**Comment by hoerup** [comment]
* Pom updated
* Travis works

**Comment by hoerup** [comment]
@TheLQ  it looks like your bitbucket mirror is out of sync anyways

**Comment by hoerup** [comment]
http://pircbotx.github.io/pircbotx/ seems to be working just fine

**Comment by Cypherke** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/pircbotx/pircbotx/2.2-SNAPSHOT/ seems to be updating too

**Comment by hoerup** [comment]
I think we're done
