### ISSUE TITLE
Sending a message containing multiple lines results in all lines after the first being run as raw IRC commands. 

### ISSUE THREAD

**Issue by lpreams** [pircbotx/pircbotx#344]
`event.getBot().send().message("#channel", "Hello world\nKICK #channel foobar")` will send the string "Hello world" to the channel, then would attempt to kick foobar out of the channel. 

I found this out the hard way after using PircBotX to make a bridge bot to a Discord server. Since Discord allows a single message to contain multiple lines, and I was giving the entire message from Discord to `send().message()`, all lines after the first were being treated as IRC commands. This behavior isn't mentioned anywhere in the docs (at least not that I could find), and I'm fairly certain it isn't the intended behavior. The behavior I expected (and have since implemented myself in my bot) is to send each line of the message string as individual messages (or at the very least replace newlines with spaces so that this doesn't happen). 

I haven't taken the time to dig through the PircBotX code to find where message sending is handled, nor have I tested whether things like `event.respond()` behave the same way (but I would guess that they do).

**Comment by hoerup** [comment]
IRC is a line based protocol - AND it's up to and programmer using any irc library to sanitize any user provided input before sending

**Comment by lpreams** [comment]
Yeah, I understand why it happens. I still think the framework should sanitize something like this. 

At the very least, there should be a warning about this behavior in the docs.

**Comment by lilggamegenius** [comment]
Yeah, this problem was found in #337. I never found this problem when I made my bridge bot as i was replacing newlines with the newline symbol character so newlines would still be sent but not flood the chat if a user went a little heavy with the new lines

**Comment by lpreams** [comment]
Ah yeah, didn't notice that one. Closed as duplicate
