### ISSUE TITLE
ListenerAdapter/onGenericMessage - multiple user messages 

### ISSUE THREAD

**Issue by bvn13** [pircbotx/pircbotx#347]
I try example described in https://github.com/pircbotx/pircbotx/blob/latest/src/test/java/org/pircbotx/impl/PircBotXExample.java

When I let my bot into chat and we (with my friend) try to talk with my bot together, our commands intersects in bot answers. Infinite loop using WaitForQueue react on every our command don't paying attention on the author of command. But I expect that it will be user-separated.

So how to write multiuser logic?
Should I use something like state mashine stored per user?

**Comment by bvn13** [comment]
And what is the purpose of WaitForQueue?

**Comment by Cypherke** [comment]
Well if you want multi-user logic, you have to implement it. Each event has a user, so if you only want it to listen to you, implement an if event.getUser().getNick() equals yournick (although this is very easy to circumvent so i would suggest something safer, but this will get you started)

In this example the WaitForQueue is used to ignore everything but MessageEvents from that point, tbh I don't use it myself

**Comment by hoerup** [comment]
Cypherke is right - if you want multi-user then you have to implement it your self.
