### ISSUE TITLE
Misssing import 

### ISSUE THREAD

**Issue by sganderson** [pircbotx/pircbotx#353]
I'm trying to create a new project on eclipse.
I add this to my pom.xml
```xml
<dependency>
        <groupId>org.pircbotx</groupId>
        <artifactId>pircbotx</artifactId>
        <version>2.1</version>
</dependency>
```
And i try to start with 
```java
import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.types.GenericMessageEvent;

public class MyListener extends ListenerAdapter {
        @Override
        public void onGenericMessage(GenericMessageEvent event) {
                //When someone says ?helloworld respond with "Hello World"
                if (event.getMessage().startsWith("?helloworld"))
                        event.respond("Hello world!");
        }

        public static void main(String[] args) throws Exception {
                //Configure what we want our bot to do
                Configuration configuration = new Configuration.Builder()
                                .setName("PircBotXUser") //Set the nick of the bot. CHANGE IN YOUR CODE
                                .addServer("irc.freenode.net") //Join the freenode network
                                .addAutoJoinChannel("#pircbotx") //Join the official #pircbotx channel
                                .addListener(new MyListener()) //Add our listener that will be called on Events
                                .buildConfiguration();

                //Create our bot with the configuration
                PircBotX bot = new PircBotX(configuration);
                //Connect to the server
                bot.startBot();
        }
}
```
in the main page of project.
There is a lot of missing import....
import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.types.GenericMessageEvent

what's wrong?

**Comment by lilggamegenius** [comment]
Are you sure you're adding the dependencies to the pom.xml correctly? Can you upload your pom.xml so we can take a look at it? If its big, make sure to pastebin it. 
It seems like its not adding the dependency like it's supposed to. You could also try refreshing it to see if it simply hasn't updated yet.
(I use gradle so my maven knowledge is a little rusty)

**Comment by sganderson** [comment]
I think is correct is a new project from scratch. 
Here the pom.
https://pastebin.com/iRdXN99s

![image](https://user-images.githubusercontent.com/5968440/36532156-45a8fa28-17c0-11e8-8a6b-bc8fe0c79ec4.png)
seems something is added. I also refresh and use another eclipse ide but is still the same.

**Comment by lilggamegenius** [comment]
I think you're just missing the version tag for pircbot. IIRC that's required.

**Comment by sganderson** [comment]
I check version tag is present but nothing change.
I switch to gradle and it's working fine.

**Comment by lilggamegenius** [comment]
I mean't the version tag for pircbotx. From the paste bin, its missing
```xml
        <dependency>
            <groupId>org.pircbotx</groupId>
            <artifactId>pircbotx</artifactId>
        </dependency>
```
Anyway, glad it's working. I think I had the same problem before I switched to gradle too.
