### ISSUE TITLE
What difference between sendIRC() and send()

### ISSUE THREAD

**Issue by Hixon10** [pircbotx/pircbotx#354]
Hi. 

I cannot understand, why there are two equal (by implementation) methods **sendIRC()** and **send()**. When should  I use each of them? They have no any documentation. 

```
	public OutputIRC sendIRC() {
		return outputIRC;
	}
	
	public OutputIRC send() {
		return outputIRC;
	}
```

**Comment by lilggamegenius** [comment]
I may be wrong but I think `send()` is for source code compatibility when function names were changed. I would need to check the files history but I think this that's the reason.

**Comment by Hixon10** [comment]
The method **send()** is developed after the method **sendIRC()**
https://github.com/pircbotx/pircbotx/commit/81fc5e8c61042b880d17159f5261622577729a1a

By the way, I don't see any usages of **send()** in codebase. Can I deprecate it?

**Comment by lilggamegenius** [comment]
In that case, it might be a helper function, but I would need to ask.
