### ISSUE TITLE
Where the incoming files are saved?

### ISSUE THREAD

**Issue by DarkSkull91** [pircbotx/pircbotx#355]
Hi! I used this sample code:
```
@Override
	public void onIncomingFileTransfer(IncomingFileTransferEvent event) throws Exception {
                System.out.println("File receiving...");
		//Generate a file prefix
		String prefix = "pircbotxFile" + System.currentTimeMillis() + "-";
		//File suffix is the original filename plus .txt to prevent executables
		String suffix = event.getSafeFilename();
		//Create this file in the temp directory
		File file = File.createTempFile(prefix, suffix);
		System.out.println("Downloading: " + event.getRawFilename());
		//Receive the file from the user
		event.acceptAndTransfer(file);
	}
```
I cannot understand where the files are saved. I can see in the log that the bot on the channel say me that the transfer is complete.
Is it a bug or am I to be wrong?
Thanks in advance.

**Comment by lilggamegenius** [comment]
`//Create this file in the temp directory`
🤔

**Comment by DarkSkull91** [comment]
Yes... but I thought that the folder was C:\Windows\Temp instead it was something like C:\Users\username\AppData\local  etc... That code was the sample code in the repository. Anyway I resolved.
