### ISSUE TITLE
IllegalThreadStateException on using maven to build the project. Too many daemon threads being created. 

### ISSUE THREAD

**Issue by dociledevil** [pircbotx/pircbotx#357]

**Comment by Cypherke** [comment]
Please provide a little bit more information, for starters your maven config. Because the problem lies there probably...

**Comment by dociledevil** [comment]
**Stack trace** is 

`WARNING thread Thread[cluster-ClusterId{value='5b7c3738df7d5f49fcd07a7c', description='null'}-localhost:27100,5,bot.AdminBot] was interrupted but is still alive after waiting at least 15000msecs
WARNING thread Thread[cluster-ClusterId{value='5b7c3738df7d5f49fcd07a7c', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-2-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[cluster-ClusterId{value='5b7c374adf7d5f49fcd07a7d', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-3-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[cluster-ClusterId{value='5b7c376edf7d5f49fcd07a7e', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-4-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[cluster-ClusterId{value='5b7c3940df7d5f49fcd07a81', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-7-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[cluster-ClusterId{value='5b7c39a8df7d5f49fcd07a83', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-9-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[cluster-ClusterId{value='5b7cb1b0df7d5f49fcd07a94', description='null'}-localhost:27100,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[pool-26-thread-1,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[listenerPool0-thread870,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING thread Thread[listenerPool0-thread871,5,bot.AdminBot] will linger despite being asked to die via interruption
WARNING NOTE: 14 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
WARNING Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=bot.AdminBot,maxpri=10]
    java.lang.IllegalThreadStateException
     java.lang.ThreadGroup.destroy ([ThreadGroup.java:776)
     org.codehaus.mojo.exec.ExecJavaMojo.execute ([ExecJavaMojo.java:321)
     org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([DefaultBuildPluginManager.java:134)
     org.apache.maven.lifecycle.internal.MojoExecutor.execute ([MojoExecutor.java:208)
     org.apache.maven.lifecycle.internal.MojoExecutor.execute ([MojoExecutor.java:154)
     org.apache.maven.lifecycle.internal.MojoExecutor.execute ([MojoExecutor.java:146)
     org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([LifecycleModuleBuilder.java:117)
     org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([LifecycleModuleBuilder.java:81)
     org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([SingleThreadedBuilder.java:51)
     org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([LifecycleStarter.java:128)
     org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:309)
     org.apache.maven.DefaultMaven.doExecute ([DefaultMaven.java:194)
     org.apache.maven.DefaultMaven.execute ([DefaultMaven.java:107)
     org.apache.maven.cli.MavenCli.execute ([MavenCli.java:955)
     org.apache.maven.cli.MavenCli.doMain ([MavenCli.java:290)
     org.apache.maven.cli.MavenCli.main ([MavenCli.java:194)
     jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([Native Method)
     jdk.internal.reflect.NativeMethodAccessorImpl.invoke ([NativeMethodAccessorImpl.java:62)
     jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke ([DelegatingMethodAccessorImpl.java:43)
     java.lang.reflect.Method.invoke ([Method.java:564)
     org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([Launcher.java:289)
     org.codehaus.plexus.classworlds.launcher.Launcher.launch ([Launcher.java:229)
     org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([Launcher.java:415)
     org.codehaus.plexus.classworlds.launcher.Launcher.main ([Launcher.java:356)
INFO [------------------------------------------------------------------------
INFO [1;32mBUILD SUCCESS
INFO [------------------------------------------------------------------------
INFO Total time: 09:04 h
INFO Finished at: 2018-08-22T06:34:52+05:30
INFO Final Memory: 21M/52M
INFO [------------------------------------------------------------------------
`
**pom.xml** is 
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.MyBot</groupId>
	<artifactId>IRcBot</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.pircbotx</groupId>
			<artifactId>pircbotx</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.9.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongo-java-driver</artifactId>
			<version>3.4.3</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.25</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>25.0-jre</version>
		</dependency>
		<dependency>
			<groupId>cryptx.exchange</groupId>
			<artifactId>utilities</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-client</artifactId>
			<version>2.25.1</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.4</version>
		</dependency>
    </dependencies>
	<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
        </plugins>
	</build>
</project>`

The **maven make file** is 

`mvn compile exec:java -DcleanUpDaemonThreads=false -Dexec.mainClass=bot.AdminBot `
