### ISSUE TITLE
Bump java target version

### ISSUE THREAD

**Issue by hoerup** [pircbotx/pircbotx#359]
Are there any reason why pircbotx still targets java 1.5
if it was for android compability it should be  safe to bump to 1.8 now

@TheLQ @lilggamegenius  @Cypherke

**Comment by Cypherke** [comment]
wasn't this related to [this](https://github.com/pircbotx/pircbotx/issues/63) ?

**Comment by hoerup** [comment]
@Cypherke  please explain to me, how java compile level is related to licensing ?

**Comment by Cypherke** [comment]
oh lol, I thought this was forced on us. Nevermind, move along, nothing to see here.

**Comment by hoerup** [comment]
2.3-snapshot is using java 8
