### ISSUE TITLE
On Ping Error

### ISSUE THREAD

**Issue by XdeadrushX** [pircbotx/pircbotx#363]
In the server where I try to connect my bot it is so like than twitch,  server just send ping without args, I'm getting this response...

ERROR org.pircbotx.PircBotX - Exception encountered when parsing line PING
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

Also, I Cant get the username, channel or anything from incoming lines:

09:04:47.027 [botPool0-bot6] DEBUG o.p.h.m.ThreadedListenerManager - Recieved event UnknownEvent(line= )
09:04:51.531 [botPool0-bot4] INFO  org.pircbotx.InputParser - User;BLUE;3;1;null CHAT #xc-user :hello

As you can see it is so diferent the way to send message to other servers send nick!@host on this it is separately by ; 

 User;BLUE;3;1;null JOIN #xc-user
any help be  appreciated

**Comment by Cypherke** [comment]
What kind of server is this? This will not work with the bot, and CHAT is not a command inside the IRC rfc. So it s kind of custom. (see also [this](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands)

This would require a lot of work imho.

**Comment by hoerup** [comment]
First of, please provide the entire stacktrace for that Exception
Second provide more details of wich irc server implementation you are targeting

**Comment by hoerup** [comment]
OP didn't return with requested info
