### ISSUE TITLE
User password logged in the clear at application startup

### ISSUE THREAD

**Issue by mechjacktv** [pircbotx/pircbotx#364]
When the application is started the user's password is logged in the clear at `INFO` level logging by `org.pircbotx.output.OutputRaw`. I'd either like to see this obfuscated or dropped to `DEBUG` level logging.

**Comment by hoerup** [comment]
or you could just set another debug level for that particular class ?

**Comment by mechjacktv** [comment]
That is exactly what I'm doing now. But it's bad security practice to log passwords and this should be changed.

**Comment by mechjacktv** [comment]
I submitted a PR that should address this.

**Comment by mechjacktv** [comment]
Never mind. I found a different IRC implementation I'm going to use.
