### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by DavidGMc** [pircbotx/pircbotx#369]
Es posible usar esta biblioteca para hacer aplicaciones android ..tal como se usa con pircbot? Como aparece yaaic en play Store..

Is it possible to use this library to make android applications .. how is it used with pircbot? How yaaic appears in play Store ..

**Comment by Cypherke** [comment]
Should be possible... I don't see why not. I think it will be easier to use if this pull request gets committed: https://github.com/pircbotx/pircbotx/pull/367

Though I would advice against any app with irc connection as this is not meant to be used in a mixed wifi/gprs environment.

**Comment by hoerup** [comment]
Not really a pircbotx question
