### ISSUE TITLE
Incompatible types?

### ISSUE THREAD

**Issue by ritchie-tg** [pircbotx/pircbotx#372]
Greetings,
    Could anyone help me with this issue? I've tried numerous fixes. That is a very long story, but I'll post the image below. However, the bot does not connect nor produce an error. I think my corrections are breaking the library. So how do I go about using this library in an app?

Going off the examples:
![Capture1](https://user-images.githubusercontent.com/29179921/58763267-af6e3e80-8526-11e9-8397-6e9cf31dc5c5.PNG)

My corrections:
![Capture4](https://user-images.githubusercontent.com/29179921/58763337-518e2680-8527-11e9-9d2e-eba4327b5cd3.PNG)

**Comment by jenga201** [comment]
Your changes look fine.
In the first example, you just need to add ".buildConfiguration()" to the end.
For example;
```
Configuration configuration = 
    new Configuration.Builder()
    .addListener(new Listener())
    .buildConfiguration();

PircBotX pircBotX = new PircBotX(configuration);
pircBotX.startBot();

```

I would suggest logging all events to diagnose why the bot isn't connecting.
The Twitch server could tell you what is going wrong.

Log at least the onNotice and onMessage events.

**Comment by hoerup** [comment]
requester never responded, so closing this
