### ISSUE TITLE
DCC Chat connection inside a Docker container

### ISSUE THREAD

**Issue by jenga201** [pircbotx/pircbotx#373]
I am trying to create a passive DCC connection to PircBotX sitting in a docker container.

This is the relevant DCC connection code;
```
cb.setDccPorts(new ArrayList<Integer>() {
	private static final long serialVersionUID = -8044208703336136080L;
{
	this.add(46571);
	this.add(46572);
}});
try {
	cb.setDccPublicAddress(InetAddress.getByName({publicIp});
} catch (UnknownHostException e) {
	this.getLogger().error("Unable to set DCC public address", e);
}
```

The bot will send a DCC chat to the user like;
`{UserObj}.send().dccChat();`

Running and connecting outside of the Docker container is successful;
`21:27:39.157 DEBUG DccHandler - Sent DCC send chat request to user {user} (300000ms timeout) to connect on public address /{publicIp}:44277, local address /{publicIp}:44277`

Inside the docker container, it seems the port or connection is blocked, or PircBotX is not handling the Passive DCC as expected;
`19:31:57.997 DEBUG DccHandler - Sent DCC send chat request to user {user} (300000ms timeout) to connect on public address /{publicIp}:46571, local address /{dockerContainerIp}:46571`

The only difference is the local address uses the Docker Container IP.

The debug logs look fine to me, so I'm not sure what else can be done to enable DCC inside of Docker.

Has anyone had success with this issue?

**Comment by tobciu** [comment]
did you forward the port to the docker container? (docker run -p 46571:46571 -p 46572:46572 imagename)

**Comment by jenga201** [comment]
Thanks that works.

I was using EXPOSE in the Dockerfile which seems to do nothing.
