### ISSUE TITLE
Please include a working example of Pircbotx with Android Studio project!

### ISSUE THREAD

**Issue by roboirc** [pircbotx/pircbotx#376]
Please show a working example of Pircbotx with Android Studio project!
Trying to include the library in Android Studio app but its not working! 
Thanks!

**Comment by hoerup** [comment]
Any requests on using the library outside of a standalone daemon, is out of scope for what we can assist with.

**Comment by roboirc** [comment]
You should put this information on https://github.com/pircbotx/pircbotx

**Comment by roboirc** [comment]
Could you at least give me some pointers to a direction for getting this to work with Android and if its been attempted before? Thanks

**Comment by Cypherke** [comment]
Could you at least give us any pointers as to why it is "not working"? I've said it countless times though, android is not a platform you 'd want to start an irc connection from.

**Comment by roboirc** [comment]
Here is my code so far that tries to use pircbotx: https://pastebin.com/X1prrySS
I have to run it in a background thread because you cannot run it on UI.
And I get no notification from the program about status of the connection or what is happening so far. When I check on IRC with another nickname, my bot doesn't show up on there. Hence its not working. But Android is also Java platform, rest doesn't mean anything. If the libraries for pircbotx for android exist then it should work in android. Waiting for reply.

**Comment by hoerup** [comment]
You create your thread object but you never start the thread.

**Comment by roboirc** [comment]
Right thanks!

**Comment by roboirc** [comment]
So it finally worked after I also had to downgrade Guava Library to 18.0
Thanks!

**Comment by roboirc** [comment]
Hey hoerup, trying to make Dcc file transfer work but unable to do so. Came across this: https://github.com/pircbotx/pircbotx/issues/273

How do I set the dcc public address? Can you show me the syntax? Thanks
Also how do I set the dcc ports to be able to transfer files like on hexchat etc? Thanks

**Comment by Cypherke** [comment]
All is set through your initial configuration builder:
https://github.com/pircbotx/pircbotx/blob/164de17fa48ede85025b0dab6b5ca063688df974/src/main/java/org/pircbotx/Configuration.java#L342
https://github.com/pircbotx/pircbotx/blob/164de17fa48ede85025b0dab6b5ca063688df974/src/main/java/org/pircbotx/Configuration.java#L332

**Comment by roboirc** [comment]
What should be the range for dccPorts generally for any irc related transfer? Whats the standard range?

**Comment by roboirc** [comment]
What happens to the DCC ports if not set? Which DCC ports are used by default by Pircbotx?

**Comment by DavidGMc** [comment]
No se si ya es demasiado tarde.. Pero descubrí un proyecto IRC que funciona perfectamente en Android studio.. Basado en pircbotx..

**Comment by roboirc** [comment]
David20177: Please show me the link

**Comment by DavidGMc** [comment]
https://github.com/mattford/scoutlink
Ese proyecto usa la biblioteca pircbotx 
Para Android studio,  espera sea de utilidad.. También te escribí en uno de tus repositorios

**Comment by Cypherke** [comment]
> What happens to the DCC ports if not set? Which DCC ports are used by default by Pircbotx?

https://github.com/pircbotx/pircbotx/blob/3d9bdd959f682dfc04748d9d79275e49528d0c0a/src/main/java/org/pircbotx/dcc/DccHandler.java#L626

it uses a free ephemeral port

**Comment by roboirc** [comment]
@David20177  Please speak in english :)

**Comment by roboirc** [comment]
@David20177 Gracias!

**Comment by roboirc** [comment]
@Cypherke Thanks!

**Comment by DavidGMc** [comment]
> @David20177 Gracias!

Deberías hacer un ejemplo para Android studio con ese link de scoutlink y poder colaborarte en tu cuenta de github.
