### ISSUE TITLE
Question: Anybody get DCC file send feature working in pircbotx? Can you give me working sample code? Thanks

### ISSUE THREAD

**Issue by roboirc** [pircbotx/pircbotx#383]
Please show me how to initiate and send files via DCC in pircbotx. I can't get it to work and docs are not enough. Can anybody link me to a working example of DCC file sending in pircbotx? Thanks!

**Comment by jenga201** [comment]
I've updated the documentation for sending files;
https://github.com/pircbotx/pircbotx/wiki/Documentation#sending-files

It really is as simple as 
event.getUser().send().dccFile(new File("myFile.txt"));

I've also linked you this multiple times, but here is a full working example;
https://github.com/NIBLCO/NIBLoffer/tree/develop

I haven't put much dev time into it, but it does include 'xdcc batch', send queue, and a packlist generator.
