### ISSUE TITLE
How can I compile pircbotx by myself? Too many methods are undefined.

### ISSUE THREAD

**Issue by microaaron** [pircbotx/pircbotx#393]
I downloaded the source code of pircbotx 2.2 and imported all jars needed, but there are too many errors. Too many methods are undefined. How can I compile pircbotx by myself?
![无标题irc](https://user-images.githubusercontent.com/16946786/80926114-a9807d80-8dc7-11ea-9b93-b5bdc66b3f05.png)

**Comment by hoerup** [comment]
From https://github.com/pircbotx/pircbotx/wiki/Contributors#Environment

> PircBotX uses Project Lombok to generate Java boilerplate. If you open the PircBotX and get lots of “getXXX not found” errors visit Lombok’s downloads page for instructions on how to configure your IDE
