### ISSUE TITLE
No more proper releases?

### ISSUE THREAD

**Issue by MaggiWuerze** [pircbotx/pircbotx#403]
The last release is 2 years ago and there are a lot of changes that could use a versioned release

**Comment by TheLQ** [comment]
Interest has waned over time. I've been out of the project for years but generous maintainers have kept it going. If you are interested in helping we could use the assistance.

**Comment by hoerup** [comment]
@TheLQ 
Are the pr_actions / pr_infra2 branches something that could be merged as is or do they still need some work ??
