### ISSUE TITLE
Add Listeners on specific channels ?

### ISSUE THREAD

**Issue by infi-git** [pircbotx/pircbotx#406]
Hi, 
Is it possible to add a specific listener on a channel ?

for example, my bot is on #AAA, #BBB and #CCC, I wonder if it's possible to add a listernerAAA for the first channel and listernerBBB for the second one and ignore everything on the #CCC ?

**Comment by Cypherke** [comment]
you can filter by getting the channel from the event object and comparing it to the channel you want to trigger the listener on

**Comment by infi-git** [comment]
ok, that's what I did but I wan't sure that it was the best way ^^thx
