### ISSUE TITLE
cant download v2.3 jitpack

### ISSUE THREAD

**Issue by gulk1** [pircbotx/pircbotx#408]
build failed???????????

**Comment by hoerup** [comment]
@TheLQ we should probably relax on the mvn 3.8 requirement ?

**Comment by Cypherke** [comment]
according to [jitpack documentation](https://docs.jitpack.io/building/), if we want to use a specific version of maven we should use the [maven wrapper](https://github.com/takari/maven-wrapper).

**Comment by vgrunner4v** [comment]
Hi guys, any update on this?

**Comment by Cypherke** [comment]
As of now, we have a latest build that you can download:

	<dependency>
	    <groupId>com.github.pircbotx</groupId>
	    <artifactId>pircbotx</artifactId>
	    <version>b89a9caa97</version>
	</dependency>

I'm checking with jitpack if we can get a rebuild of the master-SNAPSHOT. I dont think we can rebuild the v2.3 release.
