### ISSUE TITLE
Last releases not on popular JAR repos

### ISSUE THREAD

**Issue by jimklimov** [pircbotx/pircbotx#414]
* https://mvnrepository.com/artifact/org.pircbotx/pircbotx only has 2.1 and older
* https://jitpack.io/#pircbotx/pircbotx has 2.2 but failed to build 2.3 (maven version error)

The latter is related to #412, #409, #408 and https://github.com/jitpack/jitpack.io/issues/5305

Since the fixes seem to be in tree, maybe cutting a 2.4 release is worthwhile, to get it published?

**Comment by jimklimov** [comment]
Note: this blocks an update of https://github.com/jenkinsci/ircbot-plugin which relied on a version dubbed "2.1-g479835f-165" (although commit 479835f is actually well after 2.2 release timeframe, and features from 2.3 seem used), whose artifacts have vanished from the repos used, so currently rebuilds of the plugin are no longer possible :'|

**Comment by jimklimov** [comment]
FWIW, just realized there's also
* https://mvnrepository.com/artifact/org.pircbotx/pircbotx/2.1 (and older) referring to http://github.com/thelq/pircbotx vs.
* https://mvnrepository.com/artifact/com.github.pircbotx/pircbotx/2.2 referring to http://github.com/pircbotx/pircbotx 

but still no "2.3"

**Comment by jimklimov** [comment]
And also, https://jitpack.io/#pircbotx/pircbotx => Branches => master-SNAPSHOT => https://jitpack.io/com/github/pircbotx/pircbotx/-v2.3-gb1b48bf-9/build.log seems OK, will use it for now... (hm, why the leading minus?)

Alternately (and perhaps more future-proof since jitpack cleans away old branch builds over time), go to https://jitpack.io/#pircbotx/pircbotx => Snapshots => pick latest commit with "Get it" e.g. https://jitpack.io/#pircbotx/pircbotx/b1b48bfb64 and scroll down to "How to" include snippets for gradle/maven/... 

A notice under the How To chapter also says:

> If the project doesn't have any [GitHub Releases](https://github.com/blog/1547-release-your-software) you can use the short commit hash or 'master-SNAPSHOT' as the version.

The hash did not work for me (apparently rolled away too), but "master" as the version did satisfy maven. Not too nice for reproducibility and safety, but...

**Comment by jimklimov** [comment]
Data point: that seemed to work :) for now... ;)

**Comment by keyunder** [comment]
I wonder if the build fail comes from org.apache.commons.text.WordUtils. I tried compiling it locally and, after loading the libraries needed, it gives me an error. I go to commons-lang3:3.12 and search for the class. It's deprecated but it's there

**Comment by jimklimov** [comment]
Still a problem! At least, there was a commit in April so for a few more weeks projects that depend on newer pircbotx than the last release are buildable again... sigh :}

**Comment by jimklimov** [comment]
Sort of inched this towards "working for me" with a gross hack, by uploading the JAR from Jitpack to Jenkins snapshots (as used by plugin builds) and overriding maven-enforcer-plugin settings to accept that artifact pattern for plugin builds => https://github.com/jenkinsci/ircbot-plugin/pull/164

Very not neat, but seems workable.

Relying on a proper release would have been so much better :)

**Comment by hoerup** [comment]
https://github.com/pircbotx/pircbotx/releases/tag/2.3.1 

https://jitpack.io/#pircbotx/pircbotx/2.3.1

**Comment by jimklimov** [comment]
Yay, great - thanks! :)
